version: 2
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - govet
    - gosimple
    - ineffassign
    - deadcode
    - errcheck
    - staticcheck
    - unused
    - gosec              # security lints
    - misspell           # typo checker
    - gocyclo            # cyclomatic complexity
    - bodyclose
    - revive             # modern replacement for golint
  disable:
    - dupl               # annoying duplicate detector
    - funlen             # don't enforce function length (optional)

linters-settings:
  gocyclo:
    min-complexity: 15

  revive:
    rules:
      - name: indent-error-flow
      - name: error-return
      - name: var-naming

  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - funlen
    - text: "error should be the last type"
      linters:
        - revive

