version: "2"
run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
formatters:
  enable:
    - gofmt
    - goimports


linters-settings:
  goimports:
    local-prefixes: github.com/lablabs/pod-deletion-cost-controller
  errcheck:
    check-blank: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
